#!/bin/sh

wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.42/lolMiner_v1.42_Lin64.tar.gz
tar xvf lolMiner_v1.42_Lin64.tar.gz
cd 1.42
/lolMiner --algo TON --pool https://server1.whalestonpool.com --user EQBAIt3Hs69kCi4grIGDha7_mhF40wWG4vB83dRBsT_JXpwF
